[tool.towncrier]
    package = "galaxy_importer"
    directory = "CHANGES/"
    filename = "CHANGES.rst"
    title_format = "galaxy-importer {version} ({project_date})"
    issue_format = "`AAH-{issue} <https://issues.redhat.com/browse/AAH-{issue}>`_"


[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    # pyflakes
    "F",
    # pycodestyle errors
    "E",
    # pycodestyle warnings
    "W",
    # flake8-builtins
    "A",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # flake8-commas
    "COM",
    # flake8-datetime
    "DTZ",
]
extend-ignore = [
    # B904 requires using `raise ... from ...` to explicitly tell what to do with "parent"
    # exception. Would be nice to fix, but ignoring for now.
    "B904",
    # COM812 Trailing comma missing
    # Incompatible with black
    "COM812",
]

[tool.ruff.lint.flake8-builtins]
# `license()` buit-in function is added by the site module.
builtins-ignorelist = ["id", "dir", "license"]

[tool.coverage.run]
relative_files = true
branch = true

[tool.coverage.report]
fail_under = 95.50
precision = 2
