[tool.towncrier]
    package = "galaxy_importer"
    directory = "CHANGES/"
    filename = "CHANGES.rst"
    title_format = "galaxy-importer {version} ({project_date})"
    issue_format = "`AAH-{issue} <https://issues.redhat.com/browse/AAH-{issue}>`_"


[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    # pyflakes
    "F",
    # pycodestyle errors
    "E",
    # pycodestyle warnings
    "W",
]

[tool.coverage.run]
relative_files = true
branch = true

[tool.coverage.report]
fail_under = 95.50
precision = 2
