[tool.towncrier]
    package = "galaxy_importer"
    directory = "CHANGES/"
    filename = "CHANGES.rst"
    title_format = "galaxy-importer {version} ({project_date})"
    issue_format = "`#{issue} <https://github.com/ansible/galaxy_ng/issues/{issue}>`_"
