[tool.towncrier]
    package = "galaxy_importer"
    directory = "CHANGES/"
    filename = "CHANGES.rst"
    title_format = "galaxy-importer {version} ({project_date})"
    issue_format = "`AAH-{issue} <https://issues.redhat.com/browse/AAH-{issue}>`_"
