apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {build_name}
  labels:
    app: automation-hub
spec:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  output:
    to:
      kind: ImageStreamTag
      name: {image_name}
  source:
    dockerfile: |
      FROM ansible/default-test-container:latest
      RUN wget '{download_url}' -O /archive/archive.tar.gz
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ansible-test:stable
  triggers:
  - type: ConfigChange
  imagePullPolicy: IfNotPresent
