apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {build_name}
  labels:
    app: automation-hub
spec:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  output:
    to:
      kind: ImageStreamTag
      name: {image_name}
  source:
    dockerfile: |
      FROM quay.io/awcrosby/galaxy-ansible-test:v0.2.7
      RUN wget '{download_url}' -O /archive/archive.tar.gz
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: quay-cloudservices-pull
  triggers:
  - type: ConfigChange
  imagePullPolicy: IfNotPresent
