apiVersion: batch/v1
kind: Job
metadata:
  name: {job_name}
  labels:
    app: automation-hub
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 0
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {job_name}
        image: {image}
        resources:
          requests:
            cpu: {cpu_request}
            memory: {memory_request}
          limits:
            cpu: {cpu_limit}
            memory: {memory_limit}
      restartPolicy: Never
      imagePullPolicy: IfNotPresent
