apiVersion: batch/v1
kind: Job
metadata:
  name: {job_name}
  labels:
    app: automation-hub
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 0
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {job_name}
        image: {image}
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
      restartPolicy: Never
      imagePullPolicy: IfNotPresent
