apiVersion: batch/v1
kind: Job
metadata:
  name: {job_name}
  labels:
    app: automation-hub
spec:
  activeDeadlineSeconds: {job_timeout}
  backoffLimit: 0
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {job_name}
        image: quay.io/cloudservices/automation-hub-ansible-test:a53df53
        resources:
          requests:
            cpu: {cpu_request}
            memory: {memory_request}
          limits:
            cpu: {cpu_limit}
            memory: {memory_limit}
        env:
        - name: ARCHIVE_URL
          value: {archive_url}
      imagePullSecrets:
      - name: quay-cloudservices-pull
      restartPolicy: Never
      imagePullPolicy: IfNotPresent
