---
name: PullRequest CI
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: make venv
        run: python3 -m venv /tmp/venv && source /tmp/venv/bin/activate && pip install -e .[dev]

      - name: run the integration tests
        run: source /tmp/venv/bin/activate && make test/integration
