---

name: Commit Check used in GalaxyNG


# Events that trigger workflow
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'  # double asterisk would include this workflow on push to a fork

# Jobs can run sequentially or in parallel
jobs:
  commit-check:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.after }}  # for PR avoids checking out merge commit
          fetch-depth: 0  # include all history

      - name: Run script to validate commits for both pull request and a push
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          GITHUB_PULL_REQUEST: ${{ github.event.number }}
          GITHUB_PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
          GITHUB_BRANCH: ${{ github.head_ref }}
          GITHUB_REPO_SLUG: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ github.event.pull_request.commits_url }}
          GITHUB_PR_COMMITS_URL: ${{ github.event.pull_request.commits_url }}
          START_COMMIT: ${{ github.event.before }}
          END_COMMIT: ${{ github.event.after }}
        run: |
          curl https://raw.githubusercontent.com/ansible/galaxy_ng/master/.ci/scripts/validate_commit_message_custom.py | python
